#!/bin/bash
PATH=/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin

BADASS=()
DATA=`grep "Failed password" /var/log/secure | awk '{print $11}' | grep "[0-9]*\.[0-9]*\.[0-9]*\.[0-9]*" | sort | uniq -c`

TIME=`date`

old_IFS=$IFS
IFS=$'\n'


for i in $DATA
do
	TEST=`echo $i | awk '{ print $1 }'`
	if [ $TEST -gt 2 ]
	then
		IP=`echo $i | awk '{ print $2 }'`
		/sbin/iptables -nvL INPUT | grep "$IP" > /dev/null
		if [ $? == 1 ]
		then
			/sbin/iptables -I INPUT -p tcp -s $IP -j DROP -m comment --comment "Reason: SSH $TIME"
			BADASS+=("$IP")
		fi
	fi
done

IFS=$old_IFS

HOSTNAME=`hostname`
UNAME=`uname -a`

if [ ${#BADASS[*]} -gt 0 ]
then
	echo -e "\nZablokowane adresy - $HOSTNAME
=====================================
\n${BADASS[@]}\n
=====================================
$UNAME\n"
fi
